// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjoCEWUWdf12RM2z8h24FIDa0C8ZHoIQc',
    appId: '1:253250589547:web:ae8c302a9a6a60f69df22e',
    messagingSenderId: '253250589547',
    projectId: 'zentask-9622d',
    authDomain: 'zentask-9622d.firebaseapp.com',
    storageBucket: 'zentask-9622d.firebasestorage.app',
    measurementId: 'G-MJ13R3MVPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6G4bWrSNB-6DWuZbADISeVWyesn2zENE',
    appId: '1:253250589547:android:87522bc67a2e17119df22e',
    messagingSenderId: '253250589547',
    projectId: 'zentask-9622d',
    storageBucket: 'zentask-9622d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrXYvcI_mtWdNNDo3DYEdm2PQ5v8abnAs',
    appId: '1:253250589547:ios:c4498b1ee35de1ed9df22e',
    messagingSenderId: '253250589547',
    projectId: 'zentask-9622d',
    storageBucket: 'zentask-9622d.firebasestorage.app',
    iosBundleId: 'com.example.zentask',
  );
}
